M48
; DRILL file {KiCad 8.0.1} date 2024-06-15T21:09:56+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-15T21:09:56+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X32.0Y-16.0
T2
X3.5Y-3.5
X3.5Y-36.5
X36.5Y-3.5
X36.5Y-36.5
M30
